language: java
env:
  matrix:
  - IDEA_VERSION=IC-15.0.4
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
  - secure: iHiMZKdh/i3sU8YJjqi7XVNGwzv8xHZnJPL/l6i1h26waN7awrFl7/4kxSzMtMbJotz0WweCqrVF5LhSMGpmXzXAq/zI4W4uk9WpAr51rSx1QuEbXPZcSgNpQSGT6Du6hY7md1HY24mxoKYfmfzwBhlhEYrLdIZzdtvfEqfbXIqfdvfkYvKTaRvlDRbWKzAMKkJ3njQCyqafo2Tc5vK3ZKlhMVGUK2wCTxcohvlsiMr+Bi6jTeAg1ipffmmLZS/g6SiLys+WIy//74kr9jc9vN8GZwKP08lnMghDwgI3PNp8EVXUvUphXG9aGrP4tHhRefM/GCGpbkicHh9B/qNAIlBWnR6JCK5AYr6hqkDsvH+Y0Bg2bJs590h+Z5pqq8QEZUaYOKgh5/4AJ1rOmBQ7vwxcdR/kf1d+X/xPh4zD5jLSyVKYQDI9Ww0LjnfskbEYQYKLPK/VwCVjWbGmzNhoz27Ly/D+jwmSeJj03YDvqqZiTCO40HHRt7F3yTL1jFhQitQ7pE1gHIvvI2T/3cwCH89Xv+fjgBbimCRugf8tkvNuQx33R15L2zMTCoOkWKkf4T/rpwg8BBwoR6BZ/GMaMQe3/jry90ANo3fbsi31PC4jGU6qrNYWrUAnF2XrFk7W19e9axlY+m4QdHbgsq1RV65mtuvKDlIb9Ph+aeCYbXg=
jdk:
- oraclejdk7
- oraclejdk8
script:
- ./gradlew test -PideaVersion=$IDEA_VERSION
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
before_install:
- openssl aes-256-cbc -K $encrypted_bc541a30c990_key -iv $encrypted_bc541a30c990_iv
  -in travis.enc -out ~\/.ssh/travis/travis -d
- chmod 600 .travis.ssh
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile .travis.ssh\n" >> ~/.ssh/config
